name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@v1
    - name: Check swift version
      run: swift --version # Swift 5.3.3
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Test
      run: |
        xcodebuild -workspace .swiftpm/xcode/package.xcworkspace \
        -scheme GIFImage \
        -sdk iphonesimulator \
        -toolchain "${TOOLCHAINS}" \
        -destination 'platform=iOS Simulator,name=iPhone 8' \
        clean build test