name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@v1
    - name: Check swift version
      run: swift --version # Swift 5.3.3
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Test
      run: |
        # Github Actions is only on macOS 11 which causes errors with concurrency APIs
        # during tests. Like: Library not loaded: /usr/lib/swift/libswift_Concurrency.dylib
        # So, we are running the tests, but accepting that they will fail (for now).
        # The actual tests can be configured as a pre-push on git.
        set +e

        swift test